<?php
/**
 * @category   Bitbull
 * @package    Bitbull_Bestlist
 * @author     Gennaro Vietri <gennaro.vietri@bitbull.it>
 */
/* @var $this Bitbull_Bestlist_Block_Tracking */
?>
<?php if (!Mage::helper('core/cookie')->isUserNotAllowSaveCookie()): ?>
<!-- BEGIN BESTLIST TRACKING CODEs -->
<script type="text/javascript">
//<![CDATA[
    var beslistQueue = [];
    <?php echo $this->_getOrdersTrackingCode() ?>

    (function () {
        var ba = document.createElement('script');
        ba.async = true;
        ba.src = '//pt1.beslist.nl/pt.js';
        var s = document.getElementsByTagName('script')[0];
        s.parentNode.insertBefore(ba, s);
    })();

//]]>
</script>
<!-- END BESTLIST TRACKING CODE -->
<?php endif; ?>
